### ISSUE TITLE
Request check for only time greater than 2020-01-01 for example

### ISSUE THREAD

**Issue by quydox** [gitleaks/gitleaks#1115]
Dear Team,

Thank you for great tools.

I would like to suggest that gitleaks ignores commit older than specified time

For example: gitleaks detect source . -v -min-time 2020-01-01

So all commit time less than 2020-01-01 will be ignored.

Thanks Team,

**Comment by maltemorgenstern** [comment]
Hey @quydox,
you should be able to use the `--log-opts` flag for this.

It allows you to pass custom arguments to the `git log` command (which `gitleaks` uses to identify the commits). One possible argument would be `--since=<date>`. For your example the `gitleaks` command could look like this:
```
$ gitleaks detect --log-opts="--since=2020-01-01" --verbose --source .
```
This should filter out all commits that were made before `2020-01-01`.

You can find all the available `git log` flags in the [official git log documentation](https://git-scm.com/docs/git-log) and some more details about time filtering in this [stackoverflow thread](https://stackoverflow.com/q/14618022).

Regards
Malte

**Comment by zricethezav** [comment]
Excellent explainer @maltemorgenstern! Thanks :)
