### ISSUE TITLE
.gitleaksignore bug

### ISSUE THREAD

**Issue by C1ph3R-s** [gitleaks/gitleaks#1155]
Hi,

As I tested .gitleaksignore file does not ignore anything without the proper fingerpring, is it possible a "whitecard" solution in this case?
For example, I used this sample:

acce01f2338434a78f6a4a06a097b0fd23280484:README.md:aws-access-token:218
README.md:aws-access-token:204
README.md:aws-access-token:205
README.md:aws-access-token:244

In this case gitleaks, does not ignore the README.md without the hash, so  just the first line works.

Any advise?
Thanks

**Comment by rgmz** [comment]
This could either be a bug or documentation, depending on your perspective. As a user, I would expect the following example to ignore all `aws-access-token` findings from `README.md` lines 204, 205, and 244.

https://github.com/gitleaks/gitleaks/blob/839f114f2b2ca9429300e545aa5c93a2caf2e3d8/.gitleaksignore#L658-L660

However, the code seems to only check for *exact matches*, meaning those will only apply if you perform a scan with the `--no-git` option.

https://github.com/rgmz/gitleaks/blob/839f114f2b2ca9429300e545aa5c93a2caf2e3d8/detect/detect.go#L596-L606

Ideally, it should be possible to exempt a fingerprint across ALL commits.

**Comment by defigor** [comment]
Hi,

Any updates on this one? 

We are facing the same issue and would love to be able to ignore some false positives with just specifying the file and the line. Because currently we need to create a number of PRs when we merge a branch to master that contains a gitleaks ignore and then when we merge the master branch into other branches, because the merge commits contain this change and gitleaks believes that it is a newly defined secret, so we end up with something like this:

xxxxx.README.md:204
yyyyy.README.md:204
zzzzz.README.md:204
bbbbb.README.md:204
cccccc.README.md:204

Thanks in advance!
